USE gg_hosiery;

CREATE TABLE IF NOT EXISTS website_users (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    firebase_uid VARCHAR(160) NOT NULL UNIQUE,
    name VARCHAR(160) NULL,
    email VARCHAR(190) NOT NULL UNIQUE,
    photo_url VARCHAR(255) NULL,
    last_login_at DATETIME NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;
